@startuml
skinparam linetype ortho
skinparam dpi 400

enum Rolle
{
  Operatør
  Kunde
}

class Bruger
{
  id: Integer
  rolle: Rolle
  navn: String
  email: String
}

class Færge
{
  id: Integer
  navn: String
}

enum Kategori
{
  Person
  Kæledyr
  Morgenmad
  Førsteklasse
  Køretøj
}

class Kapacitet
{
  id: Integer
  færge_id: Færge FK
  kategori: Kategori
  maksimum: Integer
}

class Havn
{
  id: Integer
  navn: String
}

class Stop
{
  id: Integer
  bruger_id: Bruger FK
  færge_id: Færge FK
  havn_id: Havn FK
  zone: String
  start: Int
  aflyst: Byte
}

class Billet
{
  id: Integer
  bruger_id: Bruger FK
  kategori: Kategori
}

class Stop_Billet
{
  id: Integer
  stop_id: Stop FK
  billet_id: Billet FK
}

enum Variant
{
  Bil
  Lastbil
  Cykel
}

class Køretøj
{
  id: Integer
  billet_id: Billet FK
  variant: Variant
  identifikationsnummer: String
}

class Person
{
  id: Integer
  billet_id: Billet FK
  fornavn: String
  efternavn: String
  fødselsdato: Date
}

Bruger -- Rolle
Billet -- Kategori
Kapacitet -- Kategori
Køretøj -- Variant

Bruger "1" -right- "0..*" Stop: Operatør
Færge "1" -- "0..*" Stop
Havn "1" -- "0..*" Stop
Færge "1" -- "1..*" Kapacitet

Stop "1" -- "0..*" Stop_Billet
Billet "1" -- "2..*" Stop_Billet

Bruger "1" -- "1..*" Billet: Kunde

Billet "1" -- "0..1" Køretøj
Billet "1" -- "0..1" Person

@enduml