@startuml
skinparam linetype ortho
skinparam dpi 400
skinparam nodesep 100

enum Rolle
{
  Operatør
  Kunde
}

class Bruger
{
  id: Integer
  rolle: Rolle
  navn: String
  email: String
}

enum Udrejse
{
  Frederikshavn
  Læsø
}

class Færge
{
  id: Integer
  navn: String
}

enum Kategori
{
  Person
  Kæledyr
  Morgenmad
  Førsteklasse
  Køretøj
}

class Kapacitet
{
  id: Integer
  færge_id: FK
  kategori: Kategori
  maksimum: Integer
}

class Afgang
{
  id: Integer
  operatør_id: FK
  færge_id: FK
  udrejse: Udrejse
  tidspunkt: Datetime
  aflyst: Byte
}

class Billet
{
  id: Integer
  afgang_id: FK
  kunde_id: FK
  kategori: Kategori
}

Bruger -- Rolle
Afgang -- Udrejse
Billet -- Kategori
Kapacitet -- Kategori

Bruger "1" -right- "0..*" Afgang: Operatør
Færge "1" -- "0..*" Afgang
Færge "1" -- "1..*" Kapacitet

Afgang "1" -- "0..*" Billet
Bruger "1" -- "1..*" Billet: Kunde

@enduml