@startuml
skinparam linetype ortho
skinparam dpi 400

rectangle "Testing" as testing
rectangle "Staging" as staging
rectangle "Release" as release

testing --> staging : Test godkendt
staging --> release : Manuel godkendelse

@enduml