```puml
@startuml
skinparam linetype ortho
skinparam dpi 400

rectangle Operatør

rectangle Afgang
rectangle Færge
rectangle Havn

rectangle Kunde

rectangle Billet
rectangle Personbillet
rectangle Kæledyrsbillet
rectangle Morgenmadsbillet
rectangle Førsteklassebillet
rectangle Køretøjsbillet
rectangle Cykelbillet
rectangle Bilbillet
rectangle Lastbilbillet
rectangle Cykel
rectangle Bil
rectangle Lastbil
rectangle Person

Operatør "1" -- "1..*" Afgang
Operatør "1" -- "1..*" Færge

Færge "1" -- "0..*" Afgang
Havn "1" -- "0..*" Afgang
Afgang "1" -- "1..*" Billet

Kunde "1" -- "1..*" Billet

Personbillet -up-|> Billet
Kæledyrsbillet -up-|> Billet
Morgenmadsbillet -up-|> Billet
Førsteklassebillet -up-|> Billet
Køretøjsbillet -up-|> Billet

Personbillet "1" -- "1" Person

Cykelbillet -up-|> Køretøjsbillet
Cykelbillet "1" -- "1" Cykel

Bilbillet -up-|> Køretøjsbillet
Bilbillet "1" -- "1" Bil

Lastbilbillet -up-|> Køretøjsbillet
Lastbilbillet "1" -- "1" Lastbil

@enduml
```