name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: debian:13

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y \
            python3 \
            python3-flask \
            python3-flask-cors

      - name: Run tests
        run: ./build.sh test